kind: pipeline
name: lint

steps:
- name: lint
  image: imolein/luarocks:5.3
  commands:
    - luarocks install luacheck
    - luacheck src/gambiarra.lua
    - luacheck spec/gambiarra_test.lua

---
kind: pipeline
name: lua5.1

steps:
- name: test
  image: imolein/lua:5.1
  commands:
    - lua spec/gambiarra_test.lua

trigger:
  status: 
    - success

depends_on: 
  - lint

---
kind: pipeline
name: lua5.2

steps:
- name: test
  image: imolein/lua:5.2
  commands:
    - lua spec/gambiarra_test.lua

trigger:
  status: 
    - success

depends_on:
  - lint

---
kind: pipeline
name: lua5.3

steps:
- name: test
  image: imolein/lua:5.3
  commands:
    - lua spec/gambiarra_test.lua

trigger:
  status:
    - success

depends_on: 
  - lint