---
kind: pipeline
name: lua5.1

steps:
- name: test
  image: imo/lua5.1:latest
  commands:
    - lua gambiarra_test.lua

---
kind: pipeline
name: lua5.2

steps:
- name: test
  image: imo/lua5.2:latest
  commands:
    - lua gambiarra_test.lua

---
kind: pipeline
name: lua5.3

steps:
- name: test
  image: imo/lua5.3:latest
  commands:
    - lua gambiarra_test.lua