kind: pipeline
type: docker
name: lint

steps:
- name: lint
  image: imolein/luarocks:5.3
  commands:
    - luarocks install luacheck
    - luacheck src/gambiarra.lua
    - luacheck spec/gambiarra_test.lua

---
kind: pipeline
type: docker
name: lua5.1

trigger:
  status:
    - success

depends_on:
  - lint

steps:
- name: test
  image: imolein/lua:5.1
  commands:
    - lua spec/gambiarra_test.lua
---
kind: pipeline
type: docker
name: lua5.2

trigger:
  status:
    - success

depends_on:
  - lint

steps:
- name: test
  image: imolein/lua:5.2
  commands:
    - lua spec/gambiarra_test.lua

---
kind: pipeline
type: docker
name: lua5.3

trigger:
  status:
    - success

depends_on:
  - lint

steps:
- name: test
  image: imolein/lua:5.3
  commands:
    - lua spec/gambiarra_test.lua

---
kind: pipeline
type: docker
name: lua5.4

trigger:
  status:
    - success

depends_on:
  - lint

steps:
- name: test
  image: imolein/lua:5.4-beta
  commands:
    - lua spec/gambiarra_test.lua
